POST http://localhost:3003/api/drinks/
Content-Type: application/json

  {
      "name": "Mini Mary",
      "ingredients": [
        [
          "vodka",
          2,
          "cl"
        ],
        [
          "tomato juice",
          2,
          "cl"
        ],
        [
          "hot chili sauce",
          1,
          "drop"
        ],
        [
          "fresh lemon juice",
          1,
          "dash"
        ],
        [
          "worcestershire sauce",
          4,
          "dash"
        ],
        [
          "salt and pepper",
          null,
          null
        ],
        [
          "celery",
          null,
          null
        ]
      ],
      "imageUrl": "https://mixer-logic-p2images.s3.eu-central-1.amazonaws.com/miniMary.jpg",
      "glass": "shot",
      "method": [
        "shake"
      ],
      "garnish": [
        "cherry tomato",
        "celery stalk"
      ],
      "categories": [
        "shot",
        "short drinks"
      ],
      "alcohols": [
        "vodka"
      ],
      "page": 33,
      "credits": [
        [
          "Finlandia Vodka",
          "image"
        ],
        [
          "Finlandia Vodka",
          "recipe"
        ]
      ],
      "steps": [
        "Put the salt, the juices and the sauces in an ice-filled shaker",
        "Introduce the vodka to the ingredients in the ice-filled shaker",
        "Shake and strain into a shot glass.",
        "Finish with black pepper and celery."
      ]
    }